<a href="https://colab.research.google.com/github/Wonderingleon/Python/blob/main/Python_mise_%C3%A0_l'%C3%A9chelle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Mise à l'echelle

In [ ]:
import numpy as np
from sklearn import preprocessing

In [ ]:
X_appr = np.array([[25.,1.82,2.],
                  [45.,1.65,-1],
                  [55.,1.70,0.]])

Min Max Scaler

In [ ]:
MM_ME = preprocessing.MinMaxScaler()
X_ME1 = MM_ME.fit_transform(X_appr)
X_ME1

array([[0.        , 1.        , 1.        ],
       [0.66666667, 0.        , 0.        ],
       [1.        , 0.29411765, 0.33333333]])

In [ ]:
X_appr.min(0)

array([25.  ,  1.65, -1.  ])

In [ ]:
X_appr.ptp(0)

array([30.  ,  0.17,  3.  ])

In [ ]:
(X_appr- X_appr.min(0))/ X_appr.ptp(0)

array([[0.        , 1.        , 1.        ],
       [0.66666667, 0.        , 0.        ],
       [1.        , 0.29411765, 0.33333333]])

Robust Scaler

In [ ]:
R_ME = preprocessing.RobustScaler()
X_ME2 = R_ME.fit_transform(X_appr)
X_ME2

array([[-1.33333333,  1.41176471,  1.33333333],
       [ 0.        , -0.58823529, -0.66666667],
       [ 0.66666667,  0.        ,  0.        ]])