<a href="https://colab.research.google.com/github/Wonderingleon/Python/blob/main/Python_Valeurs_Vecteurs_propres.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import numpy.linalg as la

In [ ]:
Mat = np.matrix([[4,5],[2,3]])
Mat

matrix([[4, 5],
        [2, 3]])

In [ ]:
Val_p=la.eigvals(Mat)
Val_p

array([6.70156212, 0.29843788])

In [ ]:
Val_p, Vec_p=la.eig(Mat)

In [ ]:
Vec_1, Vec_2 = Vec_p[:,0],Vec_p[:,1]
Vec_1,Vec_2

(matrix([[0.87979045],
         [0.47536171]]),
 matrix([[-0.80372182],
         [ 0.59500525]]))

In [ ]:
Vec_2*Val_p[1],Mat*Vec_2

(matrix([[-0.23986104],
         [ 0.1775721 ]]),
 matrix([[-0.23986104],
         [ 0.1775721 ]]))